name: Build Kernel
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison build-essential ccache curl flex g++-multilib gcc-multilib clang libxml2-utils lzop make libssl-dev libncurses5-dev
          # পাইথন ২ এর পরিবর্তে পাইথন ৩ লিঙ্ক করা
          sudo ln -sf /usr/bin/python3 /usr/bin/python

      - name: Setup Toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git -b lineage-18.1 gcc64

      - name: KernelSU Setup
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$GITHUB_WORKSPACE/gcc64/bin/aarch64-linux-android-
          
          # কনফিগারেশন এরর এড়াতে ডিফল্ট কনফিগ ব্যবহার
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE olive-perf_defconfig
          
          # কনফিগ প্রম্পটগুলো এড়িয়ে স্বয়ংক্রিয়ভাবে বিল্ড করার কমান্ড
          yes "" | make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE oldconfig
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE -j$(nproc)
