name: Build Kernel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Toolchain
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git -b lineage-18.1 gcc64

      - name: Setup Build Environment
        run: |
          sudo apt-get update && sudo apt-get install -y git bc bison build-essential ccache curl flex g++-multilib gcc-multilib clang libxml2-utils lzop make libssl-dev libncurses5-dev python-is-python2

      - name: KernelSU Setup
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$GITHUB_WORKSPACE/gcc64/bin/aarch64-linux-android-
          chmod +x scripts/gcc-wrapper.py
          
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE olive-perf_defconfig
          
          sed -i 's/CONFIG_CC_STACKPROTECTOR_STRONG=y/CONFIG_CC_STACKPROTECTOR_NONE=y/' .config
          
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE olddefconfig
          
          make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE -j$(nproc)
          
